include:
  # 左手（peripheral）
  - board: seeeduino_xiao_ble
    shield: glove0x0a_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y

  # 右手（central）
  - board: seeeduino_xiao_ble
    shield: glove0x0a_right
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
