# ZMK SPRIT-PERI
CONFIG_ZMK_KEYBOARD_NAME="glove0x0a"

# ZMK_STUDIO
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n
CONFIG_NFCT_PINS_AS_GPIOS=y

#SPRIT
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
CONFIG_ZMK_SPLIT_BLE=y

# DEVICE
CONFIG_INPUT=y
CONFIG_ZMK_BLE=y
CONFIG_ZMK_USB=n
CONFIG_ZMK_MOUSE=y

# BATTERY
CONFIG_ZMK_BATTERY_REPORTING=y

# RGB
CONFIG_ZMK_RGB_UNDERGLOW=n
CONFIG_ZMK_HID_INDICATORS=y

# KEY_SCAN
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=5
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=10

# SLEEP:10秒、DEEP_SLEEP:3分
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_TIMEOUT=10000
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=180000

# AZ1UBALL
# WS2812
# CONFIG_RGBLED_WIDGET=y
# CAPS LED
#CONFIG_ZMK_POINTING=y