# ZMK SPRIT-CENT
CONFIG_ZMK_KEYBOARD_NAME="keyboard_X4A_BLE"

# ZMK_STUDIO
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n
CONFIG_NFCT_PINS_AS_GPIOS=n

# SPRIT
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
CONFIG_ZMK_SPLIT_BLE=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=1

# DEVICE
CONFIG_INPUT=y
CONFIG_ZMK_BLE=y
CONFIG_ZMK_USB=y
CONFIG_ZMK_MOUSE=y
CONFIG_ZMK_POINTING=y

# BATTERY
CONFIG_ZMK_BATTERY_REPORTING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y

d# AZ1UBALL
# CONFIG_ZMK_AZ1UBALL=y ###################################

# WS2812
#CONFIG_ZMK_RGB_UNDERGLOW=y
#CONFIG_ZMK_EXT_POWER=n
#CONFIG_GPIO=y
#CONFIG_LED=y
#CONFIG_LED_STRIP=y
#CONFIG_WS2812_STRIP=y
#CONFIG_WS2812_STRIP_SPI=n
#CONFIG_WS2812_STRIP_GPIO=y

# RGB
CONFIG_ZMK_RGB_UNDERGLOW=n
CONFIG_RGBLED_WIDGET=y
CONFIG_RGBLED_WIDGET_INTERVAL_MS=2000
CONFIG_RGBLED_WIDGET_BATTERY_LEVEL_HIGH=75
CONFIG_RGBLED_WIDGET_BATTERY_LEVEL_LOW=30
CONFIG_RGBLED_WIDGET_BATTERY_LEVEL_CRITICAL=10
CONFIG_RGBLED_WIDGET_SHOW_LAYER_CHANGE=n
CONFIG_RGBLED_WIDGET_SHOW_LAYER_COLORS=y
#(000)BLACK/  (001)RED/  (010)GREEN/  (011)YELLOW/  (100)BLUE/(101)MAZEND/(110)CYAN/(111)WHITE
CONFIG_RGBLED_WIDGET_LAYER_1_COLOR=0
CONFIG_RGBLED_WIDGET_LAYER_2_COLOR=2
CONFIG_RGBLED_WIDGET_LAYER_3_COLOR=2
CONFIG_RGBLED_WIDGET_LAYER_4_COLOR=6
CONFIG_RGBLED_WIDGET_LAYER_5_COLOR=6

# KEY_SCAN
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=5
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=10

# CAPS LED
CONFIG_ZMK_HID_INDICATORS=y
CONFIG_ZMK_SPLIT_PERIPHERAL_HID_INDICATORS=y

# SLEEP:10秒、DEEP_SLEEP:3分
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_TIMEOUT=10000
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=180000

