name: Build ZMK Firmware
on:
  push:
    branches:
      - main
jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      board: seeeduino_xiao_ble
      shield: glove0x0a
